// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProbarGiladassss.Data.Models;

#nullable disable

namespace ProbarGiladassss.Migrations
{
    [DbContext(typeof(TestingContext))]
    partial class TestingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("ProbarGiladassss.Data.Models.Especialidad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Especialidad", (string)null);
                });

            modelBuilder.Entity("ProbarGiladassss.Data.Models.Medico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Especialidad")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Especialidad");

                    b.ToTable("Medico", (string)null);
                });

            modelBuilder.Entity("ProbarGiladassss.Data.Models.Medico", b =>
                {
                    b.HasOne("ProbarGiladassss.Data.Models.Especialidad", "EspecialidadNavigation")
                        .WithMany("Medicos")
                        .HasForeignKey("Especialidad")
                        .IsRequired();

                    b.Navigation("EspecialidadNavigation");
                });

            modelBuilder.Entity("ProbarGiladassss.Data.Models.Especialidad", b =>
                {
                    b.Navigation("Medicos");
                });
#pragma warning restore 612, 618
        }
    }
}
