GET http://localhost:5140/api/Medico

###

GET http://localhost:5140/api/Medico/1

###

POST http://localhost:5140/api/Medico
Content-Type: application/json

{
  "Nombre": "Marcelin",
  "Apellido": "Herrerrinha",
  "EspecialidadId": 3
}

###

PUT http://localhost:5140/api/Medico/1
Content-Type: application/json

{
  "Nombre": "Claudio",
  "Apellido": "Serafino",
  "EspecialidadId": 2
}

###

DELETE http://localhost:5140/api/Medico/1